import streamlit as st
import pandas as pd

# --- 1. CONFIGURATION & STATE ---
st.set_page_config(page_title="Checkout Survey", layout="centered")

# Initialize Session State
if 'current_q' not in st.session_state:
    st.session_state.current_q = 0
if 'answers' not in st.session_state:
    st.session_state.answers = []
if 'design_df' not in st.session_state:
    st.session_state.design_df = None

# --- 2. HELPER FUNCTIONS ---
def submit_answer(choice_label, scenario_id, context_label):
    st.session_state.answers.append({
        "Scenario_ID": scenario_id,
        "Context": context_label,
        "Choice": choice_label
    })
    st.session_state.current_q += 1

def clean_display_text(text, cart_value):
    """
    Optional UI Polish:
    If the text says "Add X", check if X is huge.
    If (Gap > Cart Value), just show the price to avoid confusing the user.
    """
    if "Add" in str(text):
        try:
            # Extract the gap number (rough parsing)
            parts = text.split("Add ")
            gap = int(parts[1])
            if gap > (cart_value * 1.5): # If gap is > 150% of cart
                 # Revert to just showing the price part (e.g., "Pay 59")
                 return text.split(" or")[0]
        except:
            pass
    return text

# --- 3. APP HEADER & FILE UPLOAD ---
st.title("🛍️ Checkout Experiment")

# If no data loaded, show uploader
if st.session_state.design_df is None:
    st.info("Please upload the 'shipping_topup_design.csv' file generated by the Designer App.")
    uploaded_file = st.file_uploader("Upload Design CSV", type=['csv'])
    
    if uploaded_file is not None:
        try:
            df = pd.read_csv(uploaded_file)
            # Basic validation to ensure it's the right file
            required_cols = ['Context_Cart_Value', 'Home_Display', 'Locker_Display']
            if all(col in df.columns for col in required_cols):
                st.session_state.design_df = df
                st.rerun()
            else:
                st.error("Error: CSV is missing required columns. Please use the generator script.")
        except Exception as e:
            st.error(f"Error loading file: {e}")
            
    # OPTIONAL: Load Demo Data for testing if no file
    if st.checkbox("Or use Demo Data (for testing)"):
        # Create a small dummy dataframe matching your structure
        data = {
            'Scenario_ID': [1, 2],
            'Context_Cart_Value': [240, 750],
            'Context_Label': ['Small Basket (240kr)', 'Big Basket (750kr)'],
            'Home_Display': ['Pay 59 or Add 559', 'Pay 59 or Add 149'],
            'Home_Exp_Display': ['Pay 129', 'Pay 129'],
            'Locker_Display': ['FREE', 'FREE'],
            'Locker_Exp_Display': ['Pay 49', 'Pay 49'],
            'Shop_Display': ['Pay 19 or Add 9', 'FREE']
        }
        st.session_state.design_df = pd.DataFrame(data)
        st.rerun()

    st.stop() # Stop execution here until data is loaded

# --- 4. THE SURVEY INTERFACE ---
df = st.session_state.design_df
q_idx = st.session_state.current_q

# CHECK: Are we done?
if q_idx >= len(df):
    st.balloons()
    st.success("✅ Survey Complete! Thank you.")
    
    # Results Table
    results_df = pd.DataFrame(st.session_state.answers)
    st.dataframe(results_df)
    
    # Download Button
    csv = results_df.to_csv(index=False).encode('utf-8')
    st.download_button(
        "Download Results",
        csv,
        "survey_results.csv",
        "text/csv",
        key='download-csv'
    )
    
    if st.button("Start Over"):
        st.session_state.current_q = 0
        st.session_state.answers = []
        st.rerun()

else:
    # GET CURRENT SCENARIO
    row = df.iloc[q_idx]
    cart_val = row['Context_Cart_Value']
    
    # UI Polish: Clean up the "Add 759kr" text if it's too crazy
    home_disp = clean_display_text(row['Home_Display'], cart_val)
    
    # Progress
    st.progress((q_idx) / len(df))
    st.caption(f"Question {q_idx + 1} of {len(df)}")

    # CONTEXT HEADER (Sticky-ish)
    st.markdown(f"""
    <div style="background-color:#e8f4f8; padding:20px; border-radius:10px; margin-bottom:25px; border-left: 5px solid #0099cc;">
        <h3 style="margin:0; color:#005f80;">🛒 Cart Total: {cart_val} SEK</h3>
        <p style="margin:0; color:#555;">Select your shipping method to finish checkout.</p>
    </div>
    """, unsafe_allow_html=True)

    # --- CARDS LAYOUT ---
    
    # 1. HOME DELIVERY
    st.subheader("🏠 Home Delivery")
    c1, c2 = st.columns(2)
    
    with c1:
        st.info("**Standard Home** (2-4 Days)")
        st.markdown(f"#### {home_disp}")
        if st.button("Choose Standard Home", key=f"btn_home_{q_idx}"):
            submit_answer("Home_Standard", row['Scenario_ID'], row['Context_Label'])
            st.rerun()

    with c2:
        st.warning("**Express Home** (next day)")
        st.markdown(f"#### {row['Home_Exp_Display']}")
        if st.button("Choose Express Home", key=f"btn_home_exp_{q_idx}"):
            submit_answer("Home_Express", row['Scenario_ID'], row['Context_Label'])
            st.rerun()

    st.markdown("---")

    # 2. LOCKER & SHOP
    st.subheader("📦 Pickup Points")
    c3, c4, c5 = st.columns(3)
    
    with c3:
        st.success("**Parcel Locker** (2-4 Days)")
        st.markdown(f"#### {row['Locker_Display']}")
        if st.button("Choose Locker", key=f"btn_lock_{q_idx}"):
            submit_answer("Locker_Standard", row['Scenario_ID'], row['Context_Label'])
            st.rerun()

    with c4:
        st.warning("**Express Locker** (next day)")
        st.markdown(f"#### {row['Locker_Exp_Display']}")
        if st.button("Choose Express Locker", key=f"btn_lock_exp_{q_idx}"):
            submit_answer("Locker_Express", row['Scenario_ID'], row['Context_Label'])
            st.rerun()
            
    with c5:
        # FIXED: st.secondary does not exist. Using st.info instead.
        st.info("**Store Collect** (2-4 Days)") 
        st.markdown(f"#### {row['Shop_Display']}")
        if st.button("Choose Store", key=f"btn_shop_{q_idx}"):
            submit_answer("Shop_Collect", row['Scenario_ID'], row['Context_Label'])
            st.rerun()
            
  
